services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    volumes:
      - ./db/storage/:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - STORAGE_PATH=/storage
    networks:
      - mynetwork

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "4000:4000"
    depends_on:
      - chromadb
    environment:
      - UVICORN_PORT=4000
      - IS_DOCKER=true

    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge